version: '3.5'

networks:
  api:


services:

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./storage:/var/www/html/storage:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    tty: true
    ports:
      - "8000:80"
    depends_on:
      - php
    links:
      - php
    networks:
      - api

  php:
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor/
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - api

  mongodb:
    container_name: mongodb
    image: mongo
    tty: true
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - api
    environment:
       MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
