version: '3.5'

networks:
  api:


services:

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    tty: true
    ports:
      - "8000:80"
    depends_on:
      - lumen
    links:
      - lumen
    networks:
      - api

  lumen:
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor/
    build: .
    restart: unless-stopped
    networks:
      - api
